package Pojo;
// Generated 19/11/2015 09:00:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Rol rol;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private boolean genero;
     private String username;
     private String password;
     private boolean estado;
     private Set estudiantes = new HashSet(0);
     private Set administradors = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Rol rol, String nombre, String apellido, Date fechaNacimiento, boolean genero, String username, String password, boolean estado) {
        this.idUsuario = idUsuario;
        this.rol = rol;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.genero = genero;
        this.username = username;
        this.password = password;
        this.estado = estado;
    }
    public Usuario(int idUsuario, Rol rol, String nombre, String apellido, Date fechaNacimiento, boolean genero, String username, String password, boolean estado, Set estudiantes, Set administradors) {
       this.idUsuario = idUsuario;
       this.rol = rol;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.genero = genero;
       this.username = username;
       this.password = password;
       this.estado = estado;
       this.estudiantes = estudiantes;
       this.administradors = administradors;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public boolean isGenero() {
        return this.genero;
    }
    
    public void setGenero(boolean genero) {
        this.genero = genero;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Set getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }

     @Override
    public String toString(){
        return getIdUsuario()+" - "+ getNombre()+ " - "+getApellido()+" - "+getUsername();
    }

}


