package Pojo;
// Generated 18/01/2016 09:37:35 PM by Hibernate Tools 3.6.0



/**
 * Fichaspregunta generated by hbm2java
 */
public class Fichaspregunta  implements java.io.Serializable {


     private int idFichaInt;
     private Preguntaentrenar preguntaentrenar;
     private Ficha ficha;

    public Fichaspregunta() {
    }

    public Fichaspregunta(int idFichaInt, Preguntaentrenar preguntaentrenar, Ficha ficha) {
       this.idFichaInt = idFichaInt;
       this.preguntaentrenar = preguntaentrenar;
       this.ficha = ficha;
    }
   
    public int getIdFichaInt() {
        return this.idFichaInt;
    }
    
    public void setIdFichaInt(int idFichaInt) {
        this.idFichaInt = idFichaInt;
    }
    public Preguntaentrenar getPreguntaentrenar() {
        return this.preguntaentrenar;
    }
    
    public void setPreguntaentrenar(Preguntaentrenar preguntaentrenar) {
        this.preguntaentrenar = preguntaentrenar;
    }
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }



}


