package Pojo;
// Generated 18/01/2016 09:37:35 PM by Hibernate Tools 3.6.0



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int idItem;
     private Pregunta pregunta;
     private String nombreItem;
     private String imgItem;
     private String traduccion;
     private boolean estado;

    public Item() {
    }

    public Item(int idItem, Pregunta pregunta, String nombreItem, String imgItem, String traduccion, boolean estado) {
       this.idItem = idItem;
       this.pregunta = pregunta;
       this.nombreItem = nombreItem;
       this.imgItem = imgItem;
       this.traduccion = traduccion;
       this.estado = estado;
    }
   
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getNombreItem() {
        return this.nombreItem;
    }
    
    public void setNombreItem(String nombreItem) {
        this.nombreItem = nombreItem;
    }
    public String getImgItem() {
        return this.imgItem;
    }
    
    public void setImgItem(String imgItem) {
        this.imgItem = imgItem;
    }
    public String getTraduccion() {
        return this.traduccion;
    }
    
    public void setTraduccion(String traduccion) {
        this.traduccion = traduccion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


