package Pojo;
// Generated 18/01/2016 09:37:35 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private Tipopregunta tipopregunta;
     private String enunciado;
     private String nombrePreg;
     private boolean estado;
     private Set pregConcs = new HashSet(0);
     private Set items = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int idPregunta, Tipopregunta tipopregunta, String enunciado, String nombrePreg, boolean estado) {
        this.idPregunta = idPregunta;
        this.tipopregunta = tipopregunta;
        this.enunciado = enunciado;
        this.nombrePreg = nombrePreg;
        this.estado = estado;
    }
    public Pregunta(int idPregunta, Tipopregunta tipopregunta, String enunciado, String nombrePreg, boolean estado, Set pregConcs, Set items) {
       this.idPregunta = idPregunta;
       this.tipopregunta = tipopregunta;
       this.enunciado = enunciado;
       this.nombrePreg = nombrePreg;
       this.estado = estado;
       this.pregConcs = pregConcs;
       this.items = items;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Tipopregunta getTipopregunta() {
        return this.tipopregunta;
    }
    
    public void setTipopregunta(Tipopregunta tipopregunta) {
        this.tipopregunta = tipopregunta;
    }
    public String getEnunciado() {
        return this.enunciado;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }
    public String getNombrePreg() {
        return this.nombrePreg;
    }
    
    public void setNombrePreg(String nombrePreg) {
        this.nombrePreg = nombrePreg;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getPregConcs() {
        return this.pregConcs;
    }
    
    public void setPregConcs(Set pregConcs) {
        this.pregConcs = pregConcs;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


