package Pojo;
// Generated 19/11/2015 09:00:12 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private String enunciado;
     private double dificultad;
     private double fdescuido;
     private double indiceDis;
     private String nombrePreg;
     private boolean estado;
     private Set pregConcs = new HashSet(0);
     private Set items = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int idPregunta, String enunciado, double dificultad, double fdescuido, double indiceDis, String nombrePreg, boolean estado) {
        this.idPregunta = idPregunta;
        this.enunciado = enunciado;
        this.dificultad = dificultad;
        this.fdescuido = fdescuido;
        this.indiceDis = indiceDis;
        this.nombrePreg = nombrePreg;
        this.estado = estado;
    }
    public Pregunta(int idPregunta, String enunciado, double dificultad, double fdescuido, double indiceDis, String nombrePreg, boolean estado, Set pregConcs, Set items) {
       this.idPregunta = idPregunta;
       this.enunciado = enunciado;
       this.dificultad = dificultad;
       this.fdescuido = fdescuido;
       this.indiceDis = indiceDis;
       this.nombrePreg = nombrePreg;
       this.estado = estado;
       this.pregConcs = pregConcs;
       this.items = items;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getEnunciado() {
        return this.enunciado;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }
    public double getDificultad() {
        return this.dificultad;
    }
    
    public void setDificultad(double dificultad) {
        this.dificultad = dificultad;
    }
    public double getFdescuido() {
        return this.fdescuido;
    }
    
    public void setFdescuido(double fdescuido) {
        this.fdescuido = fdescuido;
    }
    public double getIndiceDis() {
        return this.indiceDis;
    }
    
    public void setIndiceDis(double indiceDis) {
        this.indiceDis = indiceDis;
    }
    public String getNombrePreg() {
        return this.nombrePreg;
    }
    
    public void setNombrePreg(String nombrePreg) {
        this.nombrePreg = nombrePreg;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getPregConcs() {
        return this.pregConcs;
    }
    
    public void setPregConcs(Set pregConcs) {
        this.pregConcs = pregConcs;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


