package Pojo;
// Generated 18/01/2016 09:37:35 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopregunta generated by hbm2java
 */
public class Tipopregunta  implements java.io.Serializable {


     private int idTipo;
     private String nombreTipo;
     private double dificultad;
     private double fdescuido;
     private double indiceDis;
     private Set preguntas = new HashSet(0);

    public Tipopregunta() {
    }

	
    public Tipopregunta(int idTipo, String nombreTipo, double dificultad, double fdescuido, double indiceDis) {
        this.idTipo = idTipo;
        this.nombreTipo = nombreTipo;
        this.dificultad = dificultad;
        this.fdescuido = fdescuido;
        this.indiceDis = indiceDis;
    }
    public Tipopregunta(int idTipo, String nombreTipo, double dificultad, double fdescuido, double indiceDis, Set preguntas) {
       this.idTipo = idTipo;
       this.nombreTipo = nombreTipo;
       this.dificultad = dificultad;
       this.fdescuido = fdescuido;
       this.indiceDis = indiceDis;
       this.preguntas = preguntas;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public double getDificultad() {
        return this.dificultad;
    }
    
    public void setDificultad(double dificultad) {
        this.dificultad = dificultad;
    }
    public double getFdescuido() {
        return this.fdescuido;
    }
    
    public void setFdescuido(double fdescuido) {
        this.fdescuido = fdescuido;
    }
    public double getIndiceDis() {
        return this.indiceDis;
    }
    
    public void setIndiceDis(double indiceDis) {
        this.indiceDis = indiceDis;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    
        @Override
    public int hashCode() {
        int hash = 0;
        hash += (nombreTipo != null ? nombreTipo.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Tipopregunta)) {
            return false;
        }
        Tipopregunta other = (Tipopregunta) object;
        if ((this.nombreTipo == null && other.nombreTipo != null) || (this.nombreTipo != null && !this.nombreTipo.equals(other.nombreTipo))) {
            return false;
        }
        return true;
    }





}


